topology: ACTIVSg500
meters: 500

distributions:
  - paper
  - uniform
  - generator_heavy
  - load_heavy
  - sparse
  - dense

compromised_fractions:
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1

trials: 100
